name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create coverage config file
      run: |
        echo -e "[run] \nomit = eol_vimeo/migrations/*" > .coveragerc
    - name: Run Tests
      run: |
        cd .github/
        docker-compose run cms /openedx/requirements/eol_vimeo/.github/test.sh
    - name: Push changes
      run: |
        ./.github/commit.sh ${{ secrets.GITHUB_TOKEN }}